project_id = "pvgxkznweoedkvebjjpc"

[functions.send-invoice-email]
verify_jwt = false

[functions.send-overdue-reminder]
verify_jwt = false

[functions.check-overdue-invoices]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.quote-response]
verify_jwt = false
